---- final query

----last preparation of previous_application_prep

CREATE TABLE tabelas_manipuladas.previous_application_final_prep AS 
    SELECT 
        sk_id_curr, 
        COUNT(sk_id_prev) AS cnt_appl_previous,
        SUM(CASE WHEN TRIM(NAME_CONTRACT_TYPE) = 'Revolving loans' THEN 1 ELSE 0 END) AS cnt_revolving_previous,
        SUM(CASE WHEN TRIM(NAME_CONTRACT_TYPE) = 'Cash loans' THEN 1 ELSE 0 END)      AS cnt_cash_previous,
        SUM(CASE WHEN TRIM(NAME_CONTRACT_TYPE) = 'Consumer loans' THEN 1 ELSE 0 END)  AS cnt_consumer_previous,
        AVG(amt_annuity)      AS avg_amt_annuity_previous,
        AVG(amt_application)  AS avg_amt_application_previous,
        AVG(amt_credit)       AS avg_amt_credit_previous,
        AVG(amt_down_payment) AS avg_amt_down_payment_previous,
        AVG(amt_goods_price)  AS avg_amt_goods_price_previous,
        SUM(CASE WHEN TRIM(weekday_appr_process_start) IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY') THEN 1 ELSE 0 END) AS cnt_appl_start_bus_day_previous,
        SUM(CASE WHEN TRIM(weekday_appr_process_start) IN ('SATURDAY', 'SUNDAY') THEN 1 ELSE 0 END) AS cnt_appl_start_weekend_previous,
        SUM(CASE WHEN hour_appr_process_start IN (1,2,3,4,5,6) THEN 1 ELSE 0 END) AS cnt_appl_start_dawn_previous,
        SUM(CASE WHEN hour_appr_process_start IN (7,8,9,10,11,12) THEN 1 ELSE 0 END) AS cnt_appl_start_morning_previous,
        SUM(CASE WHEN hour_appr_process_start IN (13,14,15,16,17,18) THEN 1 ELSE 0 END) AS cnt_appl_start_afternoon_previous,
        SUM(CASE WHEN hour_appr_process_start IN (19,20,21,22,23,24) THEN 1 ELSE 0 END) AS cnt_appl_start_night_previous,
        MIN(rate_down_payment) AS min_rate_down_payment_previous,
        MAX(rate_interest_primary)    AS max_interest_rate_primary_previous,
        MAX(rate_interest_privileged) AS max_interest_rate_privileged_previous,
        SUM(CASE WHEN TRIM(name_cash_loan_purpose) IN ('Repair', 'Car repair') THEN 1 ELSE 0 END) AS cnt_purpose_repair_previous,
        SUM(CASE WHEN TRIM(name_cash_loan_purpose) IN ('Education', 'Business development') THEN 1 ELSE 0 END) AS cnt_purpose_edu_bus_dev_previous,
        SUM(CASE WHEN TRIM(name_cash_loan_purpose) IN ('Medicine', 'Urgent needs') THEN 1 ELSE 0 END) AS cnt_purpose_medicine_urgent_previous,
        SUM(CASE WHEN TRIM(name_cash_loan_purpose) IN ('Everyday expenses', 'Wedding / gift / holiday', 'Purchase of electronic equipment', 'Journey', 'Hobby') THEN 1 ELSE 0 END) AS cnt_purpose_superfluous_previous,
        SUM(CASE WHEN TRIM(name_cash_loan_purpose) IN ('Buying a home', 'Building a house or an annex', 'Buying a garage', 'Buying a holiday home / land') THEN 1 ELSE 0 END) AS cnt_purpose_real_estate_previous,
        SUM(CASE WHEN TRIM(name_cash_loan_purpose) IN ('Furniture', 'Gasification / water supply') THEN 1 ELSE 0 END) AS cnt_purpose_house_needs_previous,
        SUM(CASE WHEN TRIM(name_cash_loan_purpose) IN ('Buying a used car', 'Buying a new car') THEN 1 ELSE 0 END) AS cnt_purpose_car_previous,
        SUM(CASE WHEN TRIM(name_cash_loan_purpose) IN ('Payments on other loans', 'Money for a third person') THEN 1 ELSE 0 END) AS cnt_purpose_payment_previous,
        SUM(CASE WHEN TRIM(name_contract_status)   IN ('Approved') THEN 1 ELSE 0 END) AS cnt_approved_contract_previous,
        SUM(CASE WHEN TRIM(name_contract_status)   IN ('Canceled') THEN 1 ELSE 0 END) AS cnt_canceled_previous,
        SUM(CASE WHEN TRIM(name_contract_status)   IN ('Refused') THEN 1 ELSE 0 END) AS cnt_refused_previous,
        SUM(CASE WHEN TRIM(name_contract_status)   IN ('Unused offer') THEN 1 ELSE 0 END) AS cnt_unused_previous,
        SUM(CASE WHEN TRIM(name_payment_type)      IN ('Cash through the bank') THEN 1 ELSE 0 END) AS cnt_cash_bank_payment_previous,
        SUM(CASE WHEN TRIM(name_payment_type)      IN ('Cashless from the account of the employer') THEN 1 ELSE 0 END) AS cnt_cashless_employer_payment_previous,
        SUM(CASE WHEN TRIM(name_payment_type)      IN ('Non-cash from your account') THEN 1 ELSE 0 END) AS cnt_noncash_account_payment_previous,
        SUM(CASE WHEN TRIM(name_type_suite)        IN ('Unaccompanied') THEN 1 ELSE 0 END) AS cnt_unacompanied_suite_previous,
        SUM(CASE WHEN TRIM(name_type_suite)        IN ('Family') THEN 1 ELSE 0 END) AS cnt_family_suite_previous,
        SUM(CASE WHEN TRIM(name_type_suite)        IN ('Spouse, partner') THEN 1 ELSE 0 END) AS cnt_spouse_suite_previous,
        SUM(CASE WHEN TRIM(name_type_suite)        IN ('Group of people') THEN 1 ELSE 0 END) AS cnt_group_people_suite_previous,
        SUM(CASE WHEN TRIM(name_type_suite)        IN ('Children') THEN 1 ELSE 0 END) AS cnt_children_suite_previous,
        MAX(
            CASE WHEN TRIM(name_client_type) IN ('Repeater')  THEN 3
                 WHEN TRIM(name_client_type) IN ('Refreshed') THEN 2 
                 WHEN TRIM(name_client_type) IN ('New')       THEN 1 ELSE 0 END) AS max_client_type_previous,
        SUM(CASE WHEN TRIM(name_goods_category) IN ('Sport and Leisure', 'Tourism', 'Fitness') THEN 1 ELSE 0 END) AS cnt_goods_leisure_previous,        
        SUM(CASE WHEN TRIM(name_goods_category) IN ('Audio/Video', 'Consumer Electronics', 'Computers', 'Mobile', 'Photo / Cinema Equipment') THEN 1 ELSE 0 END) AS cnt_goods_electronic_previous,
        SUM(CASE WHEN TRIM(name_goods_category) IN ('Vehicles', 'Auto Accessories') THEN 1 ELSE 0 END) AS cnt_goods_vehicles_previous,
        SUM(CASE WHEN TRIM(name_goods_category) IN ('Jewelry', 'Direct Sales', 'Clothing and Accessories', 'Additional Service') THEN 1 ELSE 0 END) AS cnt_goods_superfluous_previous,
        SUM(CASE WHEN TRIM(name_goods_category) IN ('Medical Supplies', 'Medicine', 'Insurance') THEN 1 ELSE 0 END) AS cnt_goods_medicine_previous,
        SUM(CASE WHEN TRIM(name_goods_category) IN ('Homewares', 'Furniture', 'Gardening') THEN 1 ELSE 0 END) AS cnt_goods_homeware_previous,
        SUM(CASE WHEN TRIM(name_goods_category) IN ('Construction Materials', 'House Construction') THEN 1 ELSE 0 END) AS cnt_goods_construction_previous,
        SUM(CASE WHEN TRIM(name_goods_category) IN ('Office Appliances', 'Education') THEN 1 ELSE 0 END) AS cnt_goods_office_edu_previous,
        SUM(CASE WHEN TRIM(name_goods_category) IN ('Weapon') THEN 1 ELSE 0 END) AS cnt_goods_weapon_previous,
        SUM(CASE WHEN TRIM(name_portfolio) IN ('Cards') THEN 1 ELSE 0 END) AS cnt_portfolio_cards_previous,
        SUM(CASE WHEN TRIM(name_portfolio) IN ('Cash') THEN 1 ELSE 0 END) AS cnt_portfolio_cash_previous,
        SUM(CASE WHEN TRIM(name_portfolio) IN ('POS') THEN 1 ELSE 0 END) AS cnt_portfolio_pos_previous,
        SUM(CASE WHEN TRIM(name_portfolio) IN ('Cars') THEN 1 ELSE 0 END) AS cnt_portfolio_cars_previous,
        SUM(CASE WHEN TRIM(name_product_type) IN ('x-sell') THEN 1 ELSE 0 END) AS cnt_product_xsell_previous,
        SUM(CASE WHEN TRIM(name_product_type) IN ('walk-in') THEN 1 ELSE 0 END) AS cnt_product_walkin_previous,
        SUM(CASE WHEN TRIM(channel_type) IN ('Country-wide', 'Regional / Local') THEN 1 ELSE 0 END) AS cnt_channel_regional_previous,
        SUM(CASE WHEN TRIM(channel_type) IN ('Credit and cash offices', 'AP+ (Cash loan)') THEN 1 ELSE 0 END) AS cnt_channel_cash_previous,
        SUM(CASE WHEN TRIM(channel_type) IN ('Stone', 'Contact center') THEN 1 ELSE 0 END) AS cnt_channel_contact_center_previous,
        SUM(CASE WHEN TRIM(channel_type) IN ('Channel of corporate sales', 'Car dealer') THEN 1 ELSE 0 END) AS cnt_channel_corporate_car_previous,
        SUM(CASE WHEN TRIM(name_seller_industry) IN ('Consumer electronics') THEN 1 ELSE 0 END) AS cnt_seller_electronics_previous,
        SUM(CASE WHEN TRIM(name_seller_industry) IN ('Connectivity') THEN 1 ELSE 0 END) AS cnt_seller_connectivity_previous,
        SUM(CASE WHEN TRIM(name_seller_industry) IN ('Furniture') THEN 1 ELSE 0 END) AS cnt_seller_furniture_previous,
        SUM(CASE WHEN TRIM(name_seller_industry) IN ('Industry', 'Auto technology') THEN 1 ELSE 0 END) AS cnt_seller_industry_previous,
        SUM(CASE WHEN TRIM(name_seller_industry) IN ('Construction') THEN 1 ELSE 0 END) AS cnt_seller_construction_previous,
        SUM(CASE WHEN TRIM(name_seller_industry) IN ('MLM partners', 'Tourism', 'Clothing', 'Jewelry') THEN 1 ELSE 0 END) AS cnt_seller_superfluous_previous,
        MAX(cnt_payment) AS max_cnt_payment_previous,
        SUM(CASE WHEN TRIM(name_yield_group) IN ('low_normal') THEN 1 ELSE 0 END) AS cnt_yield_low_normal_previous,
        SUM(CASE WHEN TRIM(name_yield_group) IN ('low_action') THEN 1 ELSE 0 END) AS cnt_yield_low_action_previous,
        SUM(CASE WHEN TRIM(name_yield_group) IN ('high') THEN 1 ELSE 0 END) AS cnt_yield_high_previous,
        SUM(CASE WHEN TRIM(name_yield_group) IN ('middle') THEN 1 ELSE 0 END) AS cnt_yield_middle_previous,
        SUM(nflag_insured_on_approval)          AS cnt_insured_on_approval_previous,
        SUM(cnt_historical_previous)            AS cnt_historical_credit_card_previous,
        AVG(amt_balance_previous)               AS avg_amt_credit_card_balance_previous,
        AVG(amt_credit_limit_previous)          AS avg_amt_credit_card_credit_limit_previous,
        AVG(amt_drawings_atm_previous)          AS avg_amt_credit_card_drawings_atm_previous,
        AVG(amt_drawings_previous)              AS avg_amt_credit_card_drawings_previous,
        AVG(amt_drawings_other_previous)        AS avg_amt_credit_card_drawings_other_previous,
        AVG(amt_drawings_pos_previous)          AS avg_amt_credit_card_drawings_pos_previous,
        AVG(amt_inst_min_regularity_previous)   AS avg_amt_credit_card_inst_min_regularity_previous,
        AVG(amt_payment_previous)               AS avg_amt_credit_card_payment_previous,
        AVG(amt_payment_total_previous)         AS avg_amt_credit_card_payment_total_previous,
        AVG(amt_receivable_principal_previous)  AS avg_amt_credit_card_receivable_principal_previous,
        AVG(amt_recivable_previous)             AS avg_amt_credit_card_recivable_previous,
        AVG(amt_total_receivable_previous)      AS avg_amt_credit_card_total_receivable_previous,
        AVG(cnt_drawings_atm_previous)          AS avg_cnt_credit_card_drawings_atm_previous,
        AVG(cnt_drawings_previous)              AS avg_cnt_credit_card_drawings_previous,
        AVG(cnt_drawings_other_previous)        AS avg_cnt_credit_card_drawings_other_previous,
        AVG(cnt_drawings_pos_previous)          AS avg_cnt_credit_card_drawings_pos_previous,
        AVG(cnt_instalment_mature_cum_previous) AS avg_cnt_credit_card_instalment_mature_cum_previous,
        MAX(sk_dpd_previous)                    AS max_credit_card_sk_dpd_previous,
        MAX(sk_dpd_def_previous)                AS max_credit_card_sk_dpd_def_previous,
        MAX(slope_amt_balance)                  AS max_credit_card_slope_amt_balance_previous,
        MAX(slope_amt_credit_limit)             AS max_credit_card_slope_amt_credit_limit_previous,
        MAX(slope_amt_payment)                  AS max_credit_card_slope_amt_payment_previous,
        MAX(gap_days_payment_installments)      AS max_installments_gap_days_payment_previous,
        MAX(gap_amt_payment_installments)       AS max_installments_gap_amt_payment_previous,
        AVG(cnt_installment_pos_cash)           AS avg_pos_cash_cnt_installment_previous,
        AVG(cnt_installment_future_pos_cash)    AS avg_pos_cash_cnt_installment_future_previous,
        MAX(sk_dpd_pos_cash)                    AS max_pos_cash_sk_dpd_previous,
        MAX(sk_dpd_def_pos_cash)                AS max_pos_cash_sk_dpd_def_previous
    FROM tabelas_manipuladas.previous_application_prep
    GROUP BY sk_id_curr;


----last preparation of bureau

CREATE TABLE tabelas_manipuladas.bureau_final_prep AS 
    SELECT 
        sk_id_curr,
        cnt_contracts_bureau,
        amt_credit_sum_consumer_credit AS amt_credit_sum_consumer_credit_bureau,
        amt_credit_sum_debt_consumer_credit AS amt_credit_sum_debt_consumer_credit_bureau,
        amt_credit_sum_limit_consumer_credit AS amt_credit_sum_limit_consumer_credit_bureau,
        amt_credit_sum_overdue_consumer_credit AS amt_credit_sum_overdue_consumer_credit_bureau,
        amt_credit_sum_credit_card AS amt_credit_sum_credit_card_bureau,
        amt_credit_sum_debt_credit_card AS amt_credit_sum_debt_credit_card_bureau,
        amt_credit_sum_limit_credit_card AS amt_credit_sum_limit_credit_card_bureau,
        amt_credit_sum_overdue_credit_card AS amt_credit_sum_overdue_credit_card_bureau,
        amt_credit_sum_working_capital AS amt_credit_sum_working_capital_bureau,
        amt_credit_sum_debt_working_capital AS amt_credit_sum_debt_working_capital_bureau,
        amt_credit_sum_limit_working_capital AS amt_credit_sum_limit_working_capital_bureau,
        amt_credit_sum_overdue_working_capital AS amt_credit_sum_overdue_working_capital_bureau,
        amt_credit_sum_microloan AS amt_credit_sum_microloan_bureau,
        amt_credit_sum_debt_microloan AS amt_credit_sum_debt_microloan_bureau,
        amt_credit_sum_limit_microloan AS amt_credit_sum_limit_microloan_bureau,
        amt_credit_sum_overdue_microloan AS amt_credit_sum_overdue_microloan_bureau,
        days_credit AS days_credit_bureau,
        credit_day_overdue AS credit_day_overdue_bureau,
        days_credit_enddate AS days_credit_enddate_bureau,
        amt_credit_max_overdue AS amt_credit_max_overdue_bureau,
        cnt_credit_prolong AS cnt_credit_prolong_bureau,
        days_credit_update AS days_credit_update_bureau,
        historical_size AS historical_size_bureau,
        delinquency_6_mths_consumer_credit AS delinquency_6_mths_consumer_credit_bureau,
        delinquency_6_12_mths_consumer_credit AS delinquency_6_12_mths_consumer_credit_bureau,
        delinquency_12_24_mths_consumer_credit AS delinquency_12_24_mths_consumer_credit_bureau,
        delinquency_24_36_mths_consumer_credit AS delinquency_24_36_mths_consumer_credit_bureau,
        delinquency_long_consumer_credit AS delinquency_long_consumer_credit_bureau,	 
        delinquency_6_mths_credit_card AS delinquency_6_mths_credit_card_bureau,		
        delinquency_6_12_mths_credit_card AS delinquency_6_12_mths_credit_card_bureau,	
        delinquency_12_24_mths_credit_card AS delinquency_12_24_mths_credit_card_bureau,		
        delinquency_24_36_mths_credit_card AS delinquency_24_36_mths_credit_card_bureau,	
        delinquency_long_credit_card AS	delinquency_long_credit_card_bureau,
        delinquency_6_mths_working_capital AS delinquency_6_mths_working_capital_bureau,	
        delinquency_6_12_mths_working_capital AS delinquency_6_12_mths_working_capital_bureau, 	
        delinquency_12_24_mths_working_capital AS delinquency_12_24_mths_working_capital_bureau, 	
        delinquency_24_36_mths_working_capital	AS delinquency_24_36_mths_working_capital_bureau, 	
        delinquency_long_working_capital AS delinquency_long_working_capital_bureau, 		
        delinquency_6_mths_microloan AS delinquency_6_mths_microloan_bureau, 	
        delinquency_6_12_mths_microloan	AS delinquency_6_12_mths_microloan_bureau,
        delinquency_12_24_mths_microloan AS delinquency_12_24_mths_microloan_bureau,
        delinquency_24_36_mths_microloan AS delinquency_24_36_mths_microloan_bureau, 		
        delinquency_long_microloan AS delinquency_long_microloan_bureau
        FROM 
        tabelas_manipuladas.bureau_prep;	


CREATE TABLE tabelas_manipuladas.modelling_database_1 AS 
SELECT A.*, 
B.cnt_appl_previous,	  	 	
B.cnt_revolving_previous,	  	 	
B.cnt_cash_previous,	  	 	
B.cnt_consumer_previous,	  	 	
B.avg_amt_annuity_previous,	  	 	
B.avg_amt_application_previous,	  	 	
B.avg_amt_credit_previous,	  	 	
B.avg_amt_down_payment_previous,	  	 	
B.avg_amt_goods_price_previous,	  	 	
B.cnt_appl_start_bus_day_previous,	  	 	
B.cnt_appl_start_weekend_previous,	  	 	
B.cnt_appl_start_dawn_previous,	  	 	
B.cnt_appl_start_morning_previous,	  	 	
B.cnt_appl_start_afternoon_previous,	  	 	
B.cnt_appl_start_night_previous,	  	 	
B.min_rate_down_payment_previous,	  	 	
B.max_interest_rate_primary_previous,	  	 	
B.max_interest_rate_privileged_previous,	  	 	
B.cnt_purpose_repair_previous,	  	 	
B.cnt_purpose_edu_bus_dev_previous,	  	 	
B.cnt_purpose_medicine_urgent_previous,	  	 	
B.cnt_purpose_superfluous_previous,	  	 	
B.cnt_purpose_real_estate_previous,	  	 	
B.cnt_purpose_house_needs_previous,	  	 	
B.cnt_purpose_car_previous,	  	 	
B.cnt_purpose_payment_previous,	  	 	
B.cnt_approved_contract_previous,	  	 	
B.cnt_canceled_previous,	  	 	
B.cnt_refused_previous,	  	 	
B.cnt_unused_previous,	  	 	
B.cnt_cash_bank_payment_previous,	  	 	
B.cnt_cashless_employer_payment_previous,	  	 	
B.cnt_noncash_account_payment_previous,	  	 	
B.cnt_unacompanied_suite_previous,	  	 	
B.cnt_family_suite_previous,  	 	
B.cnt_spouse_suite_previous,	  	 	
B.cnt_group_people_suite_previous,	  	 	
B.cnt_children_suite_previous,	  	 	
B.max_client_type_previous,	  	 	
B.cnt_goods_leisure_previous,	  	 	
B.cnt_goods_electronic_previous,	  	 	
B.cnt_goods_vehicles_previous,	  	 	
B.cnt_goods_superfluous_previous,	  	 	
B.cnt_goods_medicine_previous,	  	 	
B.cnt_goods_homeware_previous,	  	 	
B.cnt_goods_construction_previous,	  	 	
B.cnt_goods_office_edu_previous,	  	 	
B.cnt_goods_weapon_previous,	  	 	
B.cnt_portfolio_cards_previous,	  	 	
B.cnt_portfolio_cash_previous,	  	 	
B.cnt_portfolio_pos_previous,	  	 	
B.cnt_portfolio_cars_previous,	  	 	
B.cnt_product_xsell_previous,	  	 	
B.cnt_product_walkin_previous,	  	 	
B.cnt_channel_regional_previous,	  	 	
B.cnt_channel_cash_previous,	  	 	
B.cnt_channel_contact_center_previous,	  	 	
B.cnt_channel_corporate_car_previous,	  	 	
B.cnt_seller_electronics_previous,	  	 	
B.cnt_seller_connectivity_previous,	  	 	
B.cnt_seller_furniture_previous,	  	 	
B.cnt_seller_industry_previous,	  	 	
B.cnt_seller_construction_previous,	  	 	
B.cnt_seller_superfluous_previous,	  	 	
B.max_cnt_payment_previous,	  	 	
B.cnt_yield_low_normal_previous,	  	 	
B.cnt_yield_low_action_previous,  	 	
B.cnt_yield_high_previous,	  	 	
B.cnt_yield_middle_previous,	  	 	
B.cnt_insured_on_approval_previous,	  	 	
B.cnt_historical_credit_card_previous,	  	 	
B.avg_amt_credit_card_balance_previous,	  	 	
B.avg_amt_credit_card_credit_limit_previous,	  	 	
B.avg_amt_credit_card_drawings_atm_previous,  	 	
B.avg_amt_credit_card_drawings_previous,	  	 	
B.avg_amt_credit_card_drawings_other_previous,	  	 	
B.avg_amt_credit_card_drawings_pos_previous,	  	 	
B.avg_amt_credit_card_inst_min_regularity_previous,	  	 	
B.avg_amt_credit_card_payment_previous,	  	 	
B.avg_amt_credit_card_payment_total_previous,	  	 	
B.avg_amt_credit_card_receivable_principal_previous,	  	 	
B.avg_amt_credit_card_recivable_previous,	  	 	
B.avg_amt_credit_card_total_receivable_previous,	  	 	
B.avg_cnt_credit_card_drawings_atm_previous,	  	 	
B.avg_cnt_credit_card_drawings_previous,	  	 	
B.avg_cnt_credit_card_drawings_other_previous,	  	 	
B.avg_cnt_credit_card_drawings_pos_previous,	  	 	
B.avg_cnt_credit_card_instalment_mature_cum_previous,	  	 	
B.max_credit_card_sk_dpd_previous,	  	 	
B.max_credit_card_sk_dpd_def_previous,	  	 	
B.max_credit_card_slope_amt_balance_previous,	  	 	
B.max_credit_card_slope_amt_credit_limit_previous,	  	 	
B.max_credit_card_slope_amt_payment_previous,	  	 	
B.max_installments_gap_days_payment_previous,	  	 	
B.max_installments_gap_amt_payment_previous,	  	 	
B.avg_pos_cash_cnt_installment_previous,	  	 	
B.avg_pos_cash_cnt_installment_future_previous,	  	 	
B.max_pos_cash_sk_dpd_previous,	  	 	
B.max_pos_cash_sk_dpd_def_previous,
C.cnt_contracts_bureau,	    	    	
C.amt_credit_sum_consumer_credit_bureau,	   	    	
C.amt_credit_sum_debt_consumer_credit_bureau,	   	    	
C.amt_credit_sum_limit_consumer_credit_bureau,	   	    	
C.amt_credit_sum_overdue_consumer_credit_bureau,	   	    	
C.amt_credit_sum_credit_card_bureau,	   	    	
C.amt_credit_sum_debt_credit_card_bureau,	   	    	
C.amt_credit_sum_limit_credit_card_bureau,	   	    	
C.amt_credit_sum_overdue_credit_card_bureau,	   	    	
C.amt_credit_sum_working_capital_bureau,	   	    	
C.amt_credit_sum_debt_working_capital_bureau,	   	    	
C.amt_credit_sum_limit_working_capital_bureau,	   	    	
C.amt_credit_sum_overdue_working_capital_bureau,   	    	
C.amt_credit_sum_microloan_bureau,	   	    	
C.amt_credit_sum_debt_microloan_bureau,	   	    	
C.amt_credit_sum_limit_microloan_bureau,	   	    	
C.amt_credit_sum_overdue_microloan_bureau,	   	    	
C.days_credit_bureau,	    	    	
C.credit_day_overdue_bureau,	    	    	
C.days_credit_enddate_bureau,	   	    	
C.amt_credit_max_overdue_bureau,	   	    	
C.cnt_credit_prolong_bureau,	    	    	
C.days_credit_update_bureau,	    	    	
C.historical_size_bureau,	    	    	
C.delinquency_6_mths_consumer_credit_bureau,	    	    	
C.delinquency_6_12_mths_consumer_credit_bureau,	    	    	
C.delinquency_12_24_mths_consumer_credit_bureau,	    	    	
C.delinquency_24_36_mths_consumer_credit_bureau,    	    	
C.delinquency_long_consumer_credit_bureau,	    	    	
C.delinquency_6_mths_credit_card_bureau,	    	    	
C.delinquency_6_12_mths_credit_card_bureau,	    	    	
C.delinquency_12_24_mths_credit_card_bureau,	    	    	
C.delinquency_24_36_mths_credit_card_bureau,	    	    	
C.delinquency_long_credit_card_bureau,	    	    	
C.delinquency_6_mths_working_capital_bureau,	    	    	
C.delinquency_6_12_mths_working_capital_bureau,	    	    	
C.delinquency_12_24_mths_working_capital_bureau,	    	    	
C.delinquency_24_36_mths_working_capital_bureau,	    	    	
C.delinquency_long_working_capital_bureau,	    	    	
C.delinquency_6_mths_microloan_bureau,	    	    	
C.delinquency_6_12_mths_microloan_bureau,	    	    	
C.delinquency_12_24_mths_microloan_bureau,	    	    	
C.delinquency_24_36_mths_microloan_bureau,	    	    	
C.delinquency_long_microloan_bureau
FROM
bases_kaggle.application_train AS A 
LEFT JOIN 
tabelas_manipuladas.previous_application_final_prep AS B 
ON A.sk_id_curr = B.sk_id_curr
LEFT JOIN
tabelas_manipuladas.bureau_final_prep AS C 
ON A.sk_id_curr = C.sk_id_curr;	    	
        






        
















   
     









